apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml.v2
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: logstash
    spec:
      containers:
      - env:
        - name: LS_JAVA_OPTS
          value: -Xmx256m -Xms256m
        image: logstash
        name: logstash
        ports:
        - containerPort: 5000
        - containerPort: 9600
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/logstash/config/logstash.yml
          name: logstash-claim0
        - mountPath: /usr/share/logstash/pipeline
          name: logstash-claim1
      restartPolicy: Always
      volumes:
      - name: logstash-claim0
        persistentVolumeClaim:
          claimName: logstash-claim0
      - name: logstash-claim1
        persistentVolumeClaim:
          claimName: logstash-claim1
status: {}
