version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: bind
        source: ./elasticsearch/config/certs/elastic-cert-node1.p12
        target: /usr/share/elasticsearch/config/certs/elastic-cert-node1.p12
        read_only: true
      - type: bind
        source: ./elasticsearch/config/certs/elastic-cert-node2.p12
        target: /usr/share/elasticsearch/config/certs/elastic-cert-node2.p12
        read_only: true
      - type: bind
        source: ./elasticsearch/config/certs/elastic-stack-ca.p12
        target: /usr/share/elasticsearch/config/certs/elastic-stack-ca.p12
        read_only: true
      - type: volume
        source: /srv/elasticsearch/data
        target: /usr/share/elasticsearch/data
      - type: volume
        source: /srv/elasticsearch/logs
        target: /usr/share/elasticsearch/logs
    ports:
      - "9200"
      - "9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      discovery.zen.ping.unicast.hosts: elasticsearch
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
